LiveSplit/LiveSplitOne

css/livesplit.css

More of a temporary solution since the split name text doesn't cut off where the delta text actually starts and times don't have constant widths. Probably need more divs to fix those issues, not sure.

Stop split names from expanding to multiple rows

---

src/components/LiveSplit.tsx

The previous "mousewheel" event is deprecated and no longer works in Firefox. https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel

Fix unable to scroll in Firefox

---

src/ui/LiveSplit.tsx

The previous setup with the standalone split button was too annoying to
press on mobile. Now, the split button is gone and tapping on the
timer/splits will start the timer and split. This gives bit more
screen space for mobile as well. 
Resolves #45.

Made layout the split/start button for mobile.

---

src/css/livesplit.css

The mobile specific css broke the split and layout editor on mobile (chrome for android specifically), requiring desktop mode to use them. Also, the game icon is no longer stretched in the title component.
Seperated these changes from #50

Fixed the game icon in the title component, and some mobile issues.

---

src/ui/LiveSplit.tsx
src/ui/SideBarContent.tsx
src/util/FileUtil.ts

I added support for importing and exporting layouts. As the format is different from the desktop version LiveSplit, I decided to use the extension of *.ls1l, instead of *.lsl to distinguish between the two formats. At the moment importing requires a refresh since I *could not* get it to work without a refresh. (Every other method I tried failed)
You can test my changes at https://theessenceofdarkness.github.io/livesplitone

Support for importing and exporting layouts

---

src/css/Splits.scss
src/layout/Split.tsx
src/layout/Splits.tsx

- Fix #153 by switching which background we use for the inner style and the outer style.
- Fix the background not extending fully horizontally on empty splits. You can easily reproduce this issue by just setting a background color with the default splits and layout. I fixed this by passing `maxColumns` as a prop to `Split`, but it would probably be easier if `livesplit-core` did this instead.

Fix styling on Splits component

---

.gitignore
src/css/DetailedTimer.scss
src/layout/DetailedTimer.tsx

I tried my best to handle different heights and widths, but it's hard with CSS.
Fixes #37 
I also noticed a difference between livesplit-core and the original LS - after the final split, LS still shows the segment name, but livesplit-core doesn't. In my opinion, we should be showing the last segment's name and icon after the run ends because we're still showing the comparisons for that segment.
LS: 
LSO with icon and segment name enabled:

Add support for icon and segment name in detailed timer

---

src/css/Splits.scss
src/layout/SplitLabels.tsx

I think the issue was caused by a mismatching number of divs between the split labels and the regular splits.

Fix split labels

---

src/css/Timer.scss
src/layout/Timer.tsx

For some reason, `text-shadow` doesn't seem to work on SVGs in Firefox? Not sure what's going on, but using a `drop-shadow` filter instead of `text-shadow` seems to work in both Firefox and Chrome.
Fix #142

Fix timer shadow not working in Firefox

---

src/css/Splits.scss
src/layout/Split.tsx
src/layout/SplitLabels.tsx
src/layout/Splits.tsx

Fix #186 
We were previously relying on `position: absolute` defaulting to being relative to the table row, but that assumption doesn't hold true on most browsers. I tested this in Chrome, Firefox, and Edge.

Fix regression with split background positioning on Firefox and Edge

---

README.md

At this point in time, we barely support using Electron for a desktop app so there is very little sense in having this here. If we ever get support for making a fully working electron build this can be easily added back.

Remove Mention of Electron from README.md

---

src/css/LiveSplit.scss
src/css/Markdown.scss
src/css/RunEditor.scss
src/ui/Embed.tsx
src/ui/RunEditor.tsx

Fix #94 
I also made all the run editor tabs be the same width and cleaned up some of the Run Editor logic.
As mentioned on the issue, we maybe want to also show some of the other details as well (date and platform), or potentially jusr show none of this stuff. I'm OK with either route - if we don't want to show variables, then I'll just keep the cleanup stuff in this PR.

Show variable values as leaderboard columns

---

src/css/KeyValue.scss
src/css/Splits.scss
src/layout/KeyValueGeneric.tsx
src/layout/Split.tsx
src/layout/SplitLabels.tsx
src/layout/Splits.tsx
src/ui/LiveSplit.tsx

Fix #241 
We'll still need to do another refactor to get two row mode to work for the Splits, but it should be significantly easier to get to that point from here.

Update Splits and KeyValue components to use flexbox instead of tables

---

package-lock.json
package.json
src/ui/LiveSplit.tsx
webpack.config.js

GitHub Pages usually responds with the responses expiring after 10 minutes, so if you reload LiveSplit One after 10 minutes, you are not getting any cache hits. With a service worker we can permanently store the application data and only when we publish new changes, will the old application cache entries be removed.
This allows full offline support and should make Chrome even offer to install LiveSplit One as a Portable Web App.

Implement a Service Worker

---

.github/workflows/ci.yml
.github/workflows/test-failures.json
package.json
test/rendering-test.js

- Use longer hashes so we have fewer false passing tests.
- Add support for annotations.
- Treat test failures as warnings instead of errors since they're somewhat unreliable.
- Run tests after deployment so that we don't slow down the CD process.

Improve regression testing

---

src/layout/AutoRefreshLayout.tsx
src/layout/DragAutoRefreshLayout.tsx
src/ui/SideBarContent.tsx
src/util/AutoRefresh.tsx

`requestAnimationFrame` is preferred over `setInterval` for drawing frames as it allows the browser itself to make decisions on when to draw the layout. Unfortunately, we are no longer capped at 30fps which will result in higher CPU usage, but I feel the tradeoff is acceptable here as the browser will throttle itself if needed.
On the plus side however, input latency will be lower overall and frametimes will be more consistent avoiding stuff as seen in #64.
Closes #64.

Prefer requestAnimationFrame over setInterval

---

package-lock.json
package.json
src/css/About.scss
src/type-definitions/webpack-globals.d.ts
src/ui/About.tsx
src/ui/LiveSplit.tsx
src/ui/SideBarContent.tsx
webpack.config.js

In terms of branding, I think we should stick to "LiveSplit One" everywhere rather than doing something like "LiveSplit One Web" or "LiveSplit One Desktop" (although we should still use these internally to name our repos). This kind of goes along with the whole "One" theme - LiveSplit One is a single application that works on a lot of different platforms, and the different contexts (web, desktop) are just different ways to use it.
Fix #28

Create an About dialog

---

package-lock.json
package.json
src/css/Abbreviated.scss
src/css/KeyValue.scss
src/css/Title.scss
src/layout/Abbreviated.tsx
src/layout/KeyValue.tsx
src/layout/KeyValueGeneric.tsx
src/layout/Layout.tsx
src/layout/Text.tsx
src/layout/Title.tsx
src/ui/LiveSplit.tsx
test/rendering-test.js

This implements abbreviations. For the longest time we thought it's not possible to implement them in the web, but it turns out that it can work.
This implements support for the key value pair components so far. Abbreviations are still missing for the Title component. This will need some additional support from livesplit-core.

Implement Support for Abbreviations

---

src/css/SideBarContent.scss
src/ui/SideBarContent.tsx

This fixes the sidebar buttons moving around as you go between some of the views.
Before:
After:

Fix sidebar spacing

---

src/ui/HotkeyButton.tsx

This implements gamepad support for the hotkeys. This allows controlling LiveSplit One without having to focus the browser tab. There seem to be some unfortunate limitations though. Chrome for example acquires exclusive access to the gamepads (at least on Windows with DirectInput). Firefox however doesn't, so you likely would want to use Firefox if Chrome is causing problems with your controller.
The PR in livesplit-core needs to be merged first: https://github.com/LiveSplit/livesplit-core/pull/310

Implement Gamepad Support

---

.github/workflows/ci.yml
tslint.json

We committed a linter error to master that wasn't caught by the CI because we were previously running `npm run lint` without building livesplit-core. This made the command innacurate to a proper development environment.
Moving the linter to the normal build ensures that the full setup can happen before we run the linter. This also reduces the amount of setup repetition in the `ci.yml` file. One downside (maybe) is that the linter becomes a blocker for deployment.
[Here's a build that catches the linter error.](https://github.com/LiveSplit/LiveSplitOne/runs/510162370)
@CryZe Let me know your thoughts on what approach we should take for this.

Fix linter running in CI without building livesplit-core

---

package-lock.json
package.json

The update in https://github.com/LiveSplit/LiveSplitOne/pull/298 also bumped the pngjs version that a bunch of other packages use to 4.0.0, even though they don't support it.

Update pngjs to 4.0.0

---

src/api/GameList.ts
src/api/SpeedrunCom.ts
src/css/LayoutEditor.scss
src/css/LiveSplit.scss
src/css/Sidebar.scss
src/css/SplitsSelection.scss
src/css/main.scss
src/index.tsx
src/storage/index.tsx
src/ui/DragUpload.tsx
src/ui/LiveSplit.tsx
src/ui/RunEditor.tsx
src/ui/SplitsSelection.tsx
src/util/SplitsIO.ts
test/rendering-test.js
tslint.json

Here's a draft PR for what will be the splits selection view. There's some initial changes to the IndexedDB and already shows some very unstyled splits selection view.
~~Handle all the potential race conditions like downloading splits and then closing the splits selection view while the download is happening.~~

Implement a Splits Selection View

---

.github/workflows/ci.yml

The upstream issue has been closed, so this should work again.

Install wasm-bindgen from tool-cache again

---

src/type-definitions/wasm.d.ts

It seems like wasm-bindgen generates both `livesplit_core_bg.wasm` as well as a `livesplit_core_bg.js` now. We used to import from `livesplit_core_bg` in our bindings before, which is now ambiguous.
Fixes #349

Disambiguate the import in the WASM bindings

---

src/layout/Split.tsx

Here are the splits and layout that reproduce the issue: [splits_and_layout.zip](https://github.com/LiveSplit/LiveSplitOne/files/4549823/splits_and_layout.zip). On `master`, all of the columns show up as empty, but with this fix, only the rightmost column is empty.
Fix #346

Fix empty columns affecting columns to the left

---

src/ui/LayoutEditor.tsx
src/ui/RunEditor.tsx
src/ui/Settings.tsx
src/ui/SettingsEditor.tsx
src/ui/ToggleCheckbox.tsx

- Use `checked` instead of `defaultChecked` to make sure that a toggle's value always matches the prop value.
- Assign keys to each settings row so that toggles get recreated rather than animating when switching between components.
Fix #360

Fix toggles not properly updating when switching views

---

package-lock.json
package.json
src/layout/Component.tsx
src/layout/Layout.tsx
src/layout/Separator.tsx
src/layout/Split.tsx
src/layout/Splits.tsx

Using `shouldComponentUpdate` allows us to skip updates unless the layout state actually changes. I'm not sure if we want to write our own comparison function rather than relying on `fast-deep-equal`, especially since our layout state values are guaranteed to be JSON. We could also just rely on `livesplit-core` to tell us whether a component needs to be updated.
Total scripting time when timer isn't running **(before)**: 19.6%
Total scripting time when timer isn't running **(after)**: 9.6%
Total scripting time when timer is running **(before)**: 21.5%
Total scripting time when timer is running **(after)**: 12.4%
[benchmarks.zip](https://github.com/LiveSplit/LiveSplitOne/files/4638639/benchmarks.zip)

Only re-render components when necessary

---

src/css/Timer.scss
src/layout/Timer.tsx

In most frames only the timer will be redrawn. By moving it into its own browser layer, we can reduce the amount of work the browser needs to do to redraw that layer.
You can read more about this here:
https://developers.google.com/web/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas#promote_elements_that_move_or_fade
This improves our paint times from 0.71ms
to about 60us

Improve Paint Times

---

src/ui/Embed.tsx

I'm not sure how we can test this on one.livesplit.org without just deploying these changes.
Fix #379

Add parent params to twitch embeds

---

package.json
test/rendering-test.js

This PR bumps up the hash comparison threshold to 1 so that it doesn't fail randomly (which started happening with one of the recent Chrome updates).

Add a threshold for the image hash comparison

---

src/layout/Title.tsx
src/ui/LayoutView.tsx
src/ui/LiveSplit.tsx
src/ui/TimerView.tsx

This updates livesplit-core which brings a variety of performance improvements:
- The Layout State is now being reused and thus most frames don't require any heap allocations anymore. However we still serialize everything over into a JSON string for now, which puts a lot of
garbage on the JS heap.
https://github.com/LiveSplit/livesplit-core/pull/334
- The frequent performance.now() calls we do, first look up the window and performance object every time. This tripled the amount of calls we do over into JavaScript, with each call into JavaScript being quite expensive in Chrome.
https://github.com/LiveSplit/livesplit-core/pull/335
- By introducing a timer snapshot mechanism we further reduce the calls to performance.now() to a single time.
https://github.com/LiveSplit/livesplit-core/pull/339 …

Apply all the recent performance improvements

---

src/ui/HotkeyButton.tsx

The Settings could previously be closed with the OK button while a hotkey was still being edited. This prevented the key press listener and gamepad interval from being removed properly, which resulted in "This is disposed" exceptions whenever a key was pressed. This change ensures that the hotkey button blur element covers the entire screen, which prevents exiting the Settings before a change to the hotkey is confirmed.
Fix #488

Make hotkey button blur element always appear above the sidebar

---

src/index.tsx

IndexedDB is not usable at all when you are using Firefox's private browsing. Apparently they consider this a bug in Firefox and are currently intending to fix this: https://bugzilla.mozilla.org/show_bug.cgi?id=1639542
However, some discussion seems to indicate that it may be intentional and not be fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=781982
Until (and if) they fix it, LiveSplitOne can display an alert telling users to turn off private browsing.

Alert for #493

---

buildCore.js
src/index.tsx

All browsers now support the new WebAssembly Sign Extension Instructions which improve code that casts around between small integer types. We'd like to activate a bunch more new WASM instructions, but Safari is really lacking behind quite a lot. Even just activating these requires the latest Safari / iOS version that came out just a month ago. We notify the user to update their browser / iOS version in case they have an outdated browser. iOS updates on its own over night, so I believe most people should be on the latest version and shouldn't have any problem updating in case it didn't happen yet.
Resolves #528 (mostly at least, only one feature, but we can just add more over time as they become available)

Activate the WASM Sign Extension Instructions

---

package-lock.json
package.json
src/index.tsx
src/main.tsx
src/type-definitions/scss.d.ts
webpack.config.js

By inlining a tiny amount of JS into the HTML, we can request the WASM and other JS bundles much sooner, reducing the latency a bit. This also inlines the most important styling, so that the loading screen is always properly styled. We unfortunately have to use `syncWebAssembly` here as it allows requesting the WASM file sooner than the other setting. It's not a whole lot sooner, so once they remove the setting, we can switch back without taking too much of a hit. Another thing that I did here is that the JS that we are loading is now a bigger bundle instead of smaller ones. We need to await all of them anyway, so I feel like splitting them only means that less optimizations can be done and more requests need to be sent. So there's less, but bigger bundles now. However one thing that I'm …

Inline the main JS bundle into the HTML

---

.github/workflows/ci.yml

When changing the hotkeys in the settings, it doesn't properly set the hotkeys anymore. This is because of a refactor that we merged in `livesplit-core` that unregisters the hotkeys while the `HotkeySystem` is deactivated. The hotkey settings deactivate the hotkeys so you don't accidentally split / reset / ... the timer in the background. The bug was that it was completely impossible to set hotkeys while they are deactivated.
Fixes #575

Fix Hotkeys not being set properly

---

.github/workflows/ci.yml

Apparently `-j` completely crashes the GitHub Actions runner (or at least makes it hang).

Use `make -j2` instead of `make -j`

---

.github/workflows/ci.yml

Looks like the action now supports specifying that you just want the latest LTS version without having to actually specify the specific
version.

Use the latest LTS version of node.js in the CI

---

package-lock.json
src/ui/HotkeyButton.tsx
webpack.config.js

Turns out that `keypress` is deprecated and only reacts to key presses that results in actual visible characters. `keydown` however reacts to all key presses and is not deprecated. Also this generally bumps `livesplit-core`, so this brings other improvements as well.

Update `livesplit-core` and use `keydown` event

---

src/ui/TimerView.tsx

👋 small fix - noticed that there's a bug which allows multiple websocket connections to be open at once, potentially resulting in duplicate instructions:
- go to the main timer screen
- open a connection
- navigate away (for example, click "Splits") --> connection is not closed
- open another connection
- check Devtools Network tab --> shows two connections
This PR just closes the active connection on unmount of `TimerView` if it exists.

Fix ability to have multiple active websocket connections

---

.github/workflows/ci.yml
buildCore.js
package.json

We generally want the wasm file to be as compact as possible. However because there's so many paths in Rust code that could panic, but don't ever in practice as they are meant to signal bugs, the wasm file has to keep around all those panic paths, and even worse, all the code for formatting the panic messages for all those different types that could be involved in a panic. This bloats the binary a lot. There's a nightly feature to build the standard library as part of your compilation and with that you can pass various features to the standard library, just like with any other crate. And one of those features is to remove all the formatting machinery from the panics and just immediately abort, resulting in smaller binaries. On top of that by building the standard library ourselves we also …

Build Rust's `std` with immediate abort

---

.github/workflows/ci.yml

Turns out that `wasm-bindgen` `v0.2.84` really requires us to import the main module as that's where they now dynamically set the wasm file. Additionally this improves our CI a little, by downloading a prebuilt version of `wasm-bindgen-cli`.

Fix `livesplit-core` bindings

---

.github/workflows/ci.yml

This downloads a prebuilt version of `binaryen` instead of manually building it from scratch, which takes a very long time.

Download a prebuilt version of `binaryen`

---

src/index.tsx

This attempts to use the Screen Wake Lock API to prevent the screen from turning off. This is available in iOS 16.4 now, however at least when adding the app to the home screen as a PWA, the functionality seems to be broken. Regardless, that's not something we can fix. We can instead simply always try to activate it and hopefully Apple fixes the bug soon.
https://bugs.webkit.org/show_bug.cgi?id=254545

Implement Screen Wake Lock Support

---

buildCore.js
test/rendering-test.js

This allows stepping through the Rust code. `wasm-bindgen` 0.2.89 just got released and it finally properly allows keeping the debug symbols that Rust creates around fully. Thankfully `webpack` does not pose a problem here and the debug symbols now properly work in Chrome, allowing us to step through the Rust code in the developer tools.

Allow stepping through the Rust code

---

.github/workflows/ci.yml

Apparently it now requires you to specify which WebAssembly features to activate.

Fix `wasm-opt` in CI

---

src/util/AutoRefresh.tsx

I'm not sure how `Date.now()` sneaked in there. Dates should only ever be used if the calendar is important, which is definitely not the case for managing the frame rate. Any NTP sync should haved messed with the frames before, at least to some slight degree.

Use `performance.now()` for the frames instead

---

src/ui/Settings.tsx
src/util/FontList.ts

This uses the [Local Font Access API](https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API) to query the list of fonts installed on the user's system. If we successfully query it we show a combobox with the list of fonts. Otherwise it's still a textbox. We also get information about the styles that are available for each font family. Unfortunately this comes as a string rather than individual fields, so we have to parse it. We do this by looking for specific style names in there. Since this is mostly heuristic based, instead of only showing the styles that we found, we still show all of them, but grey out those that we didn't find, but you can still select them.

Query local fonts to show a font list

---

src/css/Tooltip.scss

Tooltips can be opened on mobile (at least in Chrome on Android) by tapping on the label.

Fix tooltip positions on mobile

---

src/index.tsx
src/layout/Layout.tsx
src/storage/index.tsx
src/ui/LayoutEditor.tsx
src/ui/LayoutView.tsx
src/ui/LiveSplit.tsx
src/ui/SettingsEditor.tsx
src/ui/TimerView.tsx
src/util/AutoRefresh.tsx
src/util/FrameRate.ts

This adds the following two settings:
1. Show Control Buttons: Determines whether to show buttons beneath the timer that allow controlling it. When disabled, you have to use the hotkeys instead.
2. Frame Rate: Determines the frame rate at which to display the timer. "Battery Aware" tries determining the type of device and charging status to select a good frame rate. "Match Screen" makes the timer match the screen's refresh rate.
Additionally this fixes a bug where the fonts were not properly loaded by the time the web renderer gets created, which then cached information about the fallback fonts instead of the actual fonts.

Implement General Settings

---

src/css/TimerView.scss
src/storage/index.tsx
src/ui/SettingsEditor.tsx
src/ui/TimerView.tsx

This commit adds support for manual game time. This is useful for games that have a built-in timer and it's fine to simply type in the times that the game displays. Currently there's no support for specifying segment times instead, but that can be added later.

Implement Manual Game Time

---

src/storage/index.tsx
src/ui/LiveSplit.tsx
src/ui/RunEditor.tsx
src/ui/SplitsSelection.tsx
src/ui/TimerView.tsx
src/util/OptionUtil.ts
src/util/SplitsIO.ts

There is a [JavaScript
proposal](https://github.com/tc39/proposal-explicit-resource-management) for using `Symbol.dispose` as a way to automatically clean up resources. You do that by declaring variables like so:
```js
using resource = new Resource();
```
The variable `resource` will be automatically disposed when it goes out of scope. We used to have our own `dispose` method and `with` helper method that allows scoped access to the resource, before it gets cleaned up at the end. TypeScript already fully implements and polyfills support for it, so we can already fully switch over to it.

Switch `wasm-bindgen` bindings to `Symbol.dispose`

---

src/index.tsx

While TypeScript can polyfill almost everything regarding the `Symbol.dispose` functionality, it does not actually polyfill the symbol itself for some reason?!

Fix Symbol.dispose polyfill for old browsers

---

src/storage/index.tsx
src/ui/LiveSplit.tsx
src/ui/RunEditor.tsx
src/ui/SettingsEditor.tsx
src/ui/SplitsSelection.tsx
src/ui/TimerView.tsx

This adds settings for turning off the integration with speedrun.com and splits.io. This is useful for people who don't want to use these features and want to avoid the extra network requests. While splits.io doesn't do any automatic network requests in the background, it still adds buttons to the UI that someone may not want to see. It's also more consistent to have a toggle for both.

Allow toggling speedrun.com, splits.io integration

---

src/css/RunEditor.scss
src/css/Tooltip.scss
src/ui/LayoutEditor.tsx
src/ui/RunEditor.tsx
src/ui/SplitsSelection.tsx

This adds tooltips to all context menus. In particular, there are now tooltips available that describe the functionality of each component.

Add Tooltips to all Context Menus

---

src/ui/LiveSplit.tsx

https://github.com/LiveSplit/LiveSplitOne/issues/888#issuecomment-2132244331
When opening LiveSplit One, the service worker downloads the latest files in the background, which usually takes a few seconds. After the files are downloaded, if it detects a change, it will now show a popup message in the bottom-right corner that can be clicked to auto-refresh the page. (The message will automatically disappear after 5 seconds to avoid being too intrusive.)
https://github.com/LiveSplit/LiveSplitOne/assets/8262173/cad287d6-1ed7-48a0-9318-b86211bb9b76

Prompt when there is an update

---

src/api/LiveSplitServer.ts
src/css/About.scss
src/css/LiveSplitServerButton.scss
src/css/Tooltip.scss
src/css/main.scss
src/index.tsx
src/storage/index.tsx
src/ui/About.tsx
src/ui/HotkeyButton.tsx
src/ui/LayoutView.tsx
src/ui/LiveSplit.tsx
src/ui/RunEditor.tsx
src/ui/Settings.tsx
src/ui/SettingsEditor.tsx
src/ui/TimerView.tsx
src/util/FrameRate.ts
webpack.config.js

This moves the server connection button to the settings and cleans the entire functionality up in various ways. The server connection no longer gets closed by navigating around the application. Additionally the server URL is now being remembered between sessions.
This also improves the design of the toast messages.

Clean up and move server connection to settings

---

src/api/LiveSplitServer.ts
src/css/main.scss
src/ui/LSOEventSink.ts
src/ui/LayoutEditor.tsx
src/ui/LayoutView.tsx
src/ui/LiveSplit.tsx
src/ui/RunEditor.tsx
src/ui/SettingsEditor.tsx
src/ui/SplitsSelection.tsx
src/ui/TimerView.tsx

This makes use of the new event system that got added to `livesplit-core`. This allows the UI to react to events that happen. Right now this is used for three things:
1. Resetting a run can now ask you for confirmation of whether to save the current run if it contains new best segments or it's a new Personal Best.
2. The side bar used to refresh the comparison and timing method 10 times per second. Now we can just react to those being changed, resulting in better performance.
3. The control buttons below the timer now get disabled when they don't apply to the current situation. The pause button also changes its icon based on the state of the timer.

Use the new event system

---

src/css/About.scss
src/css/variables.scss
src/type-definitions/webpack-globals.d.ts
src/ui/About.tsx
src/util/Markdown.tsx
webpack.config.js

This improves the contributors section in the About page. It now uses flexbox to dynamically place the contributors. Additionally their avatar is now being shown.
Also the ten most recent changes are now being shown in the About page. The information is extracted from the git history. The idea is to mark commit messages with a special changelog section at the end that's specifically meant to be shown as a user facing change. It can be arbitrary markdown and looks like this (which is also the first one):
Changelog: The About page now shows the most recent changes. The contributors section has also been improved. It now shows the avatar of each contributor.

Add a changelog and improve contributors section

---

webpack.config.js

Welp, the previous PR also broke something. This should fix it.

Fix Date matching for Changelog generation

---

src/storage/index.tsx
src/ui/LSOEventSink.ts
src/ui/LiveSplit.tsx
src/ui/SettingsEditor.tsx
src/ui/SplitsSelection.tsx
src/util/AutoRefresh.tsx
webpack.config.js

This adds a save on reset setting to the general settings. When enabled, the splits are automatically saved when the timer is reset.
Changelog: You can now enable **Save On Reset** in the settings, which will automatically save the splits when you reset the timer.

Implement Save On Reset

---

src/css/Sidebar.scss
src/ui/LSOEventSink.ts
src/ui/LayoutView.tsx
src/ui/LiveSplit.tsx
src/ui/SplitsSelection.tsx
src/ui/TimerView.tsx

This adds indicators to various parts of the UI to indicate that there are unsaved changes. The indicators are mainly shown as white dots in the sidebar highlighting what is unsaved. The title is also updated to reflect this. The Badging API is also used to show a badge on the "app icon" if it's installed as a PWA. In addition to the splits, the layouts are also now properly tracked when it comes to unsaved changes.
Changelog: There are now indicators in the user interface that remind you about unsaved changes to your splits and layouts.

Add indicators for unsaved changes

---

src/storage/index.tsx
src/ui/LayoutEditor.tsx
src/ui/LayoutView.tsx
src/ui/LiveSplit.tsx
src/ui/TimerView.tsx

This changes it so the layout dimensions are not immediately saved when resizing a layout. Instead they are saved when saving the layout. Additionally resizing marks the layout as unsaved, so you don't forget about saving the new dimensions.

Save the layout dimensions when saving layout

---

src/index.tsx
src/ui/LSOEventSink.ts
src/ui/LiveSplit.tsx
src/util/FrameRate.ts

The APIs that are not supported by every browser or may not always be allowed (Battery and Wake Lock) are requested in try catch blocks. The problem was that both of them actually yield promises. If the promises fail, then those exceptions would not be caught properly, because we forgot to await them. So especially for the wake lock you would sometimes see an error message when it gets hot reloaded. This should be fixed now.
Additionally this changes the window title for when there are unsaved changes. Apparently when LiveSplit One is used as a PWA, then at least Chrome wants to always keep the app name in the title. If the title itself is changed, then it gets shown as `LiveSplit One - The new title`. By us putting an asterisk in the front of the title, the PWA then shows `LiveSplit One …

Fix some small bugs

---

src/ui/LiveSplit.tsx

When it's the first install of the service worker, or when the user clears the site data, the `controllerchange` event gets triggered. However, in these situations, we want to avoid prompting the user about an update.
Resolves #913

Skip update prompts in invalid situations

---

webpack.config.js

This adjusts the margin for the PWA Icon on iOS to roughly match the Apple guidelines, but more importantly, to just finally look good.

Fix the margin for the PWA Icon on iOS

---

src/ui/HotkeyButton.tsx
src/ui/RunEditor.tsx

This adds functionality to the run editor to allow copying comparisons. This is not only useful for copying custom comparisons, but also for "baking" the times of a generated comparison, such as the `Latest Run` or the `Average Segments` to a custom comparison that you can keep around as long as you want. This is somewhat also meant to replace the functionality of storing the current run as a Personal Best. Instead you can just store the `Latest Run` as a custom comparison after you are done with it.
Changelog: The splits editor now allows copying comparisons. This can also be used to keep the times of an automatic comparison around as a custom comparison. One example for using this is keeping around the latest run as a custom comparison, so that you can compare against it later on, even …

Allow copying comparisons

---

webpack.config.js

Before:
After:
I had to specify `offset` as well because it looked bad without it:

Use background for Android icon

---

src/index.tsx
src/storage/index.tsx
src/ui/LiveSplit.tsx
webpack.config.js

We now automatically store the current comparison and timing method into the Indexed DB. This allows us to restore the comparison and timing method when the user reloads the page.
Changelog: The comparison and timing method (Real Time / Game Time) that you choose now stay chosen when you reload LiveSplit One.

Store the comparison and timing method

---

buildCore.js

This enables the multivalue feature when building with the nightly Rust compiler. This is because the Rust standard library is not built with the multivalue feature enabled by default. Also we need to specifically use the spec compliant C ABI for it to work, which is also nightly only.

Enable the WebAssembly Multivalue feature

---

src/ui/TimerView.tsx
test/rendering-test.js

Instead of assuming each column has the width of the text `88:88:88`, we now determine the largest string per column (based on unicode scalar values) and adjust the column width accordingly. There is still a fixed minimum width based on the string `88:88`, which ensures that the columns don't switch sizes too often, especially if you start with empty splits. We could've also chosen `8:88:88`, which would ensure there's no column size change as you approach the hour mark. However, this would increase the size of delta columns unnecessarily. So it's a little bit of a trade-off.

Dynamically adjust the column widths

---

src/api/GameList.ts
src/css/Dialog.scss
src/css/main.scss
src/index.tsx
src/ui/Dialog.tsx
src/ui/LSOEventSink.ts
src/ui/LiveSplit.tsx
src/ui/RunEditor.tsx
src/ui/Settings.tsx
src/ui/SplitsSelection.tsx
src/util/FileUtil.ts
src/util/OptionUtil.tsx

This introduces custom dialogs to LiveSplit One. Previously we've used the builtin browser dialogs that are very limited in what they can do.
Additionally this introduces a bunch of smaller changes:
- The splits editor is now more optimized and only searches for the game name whenever it or the list of games changes.
- The PWA badge now resets when the app is reloaded.
- Guests on the leaderboard can now have flags.
- If a user encounters a bug, there's now dedicated toast popups that don't disappear and direct the user to the issue tracker.
- The Sum of Best cleaner now ensures the run can't be modified while the cleaning is in progress, which would lead to memory corruption, especially with the async nature of the new dialogs.
- Cancelling out of opening files doesn't lead to an error …

Introduce Custom Dialogs

---

src/css/Dialog.scss
src/css/HotkeyButton.scss
src/css/LiveSplitServerButton.scss
src/css/RunEditor.scss
src/css/Sidebar.scss
src/css/Table.scss
src/css/Toggle.scss
src/css/main.scss
src/ui/Dialog.tsx
src/ui/LSOEventSink.ts
src/ui/LiveSplit.tsx
src/ui/RunEditor.tsx
src/ui/Settings.tsx
src/ui/SplitsSelection.tsx
src/util/FileUtil.ts
src/util/SplitsIO.ts

The dialogs are now asynchronous as opposed to the browser built-in ones that are synchronous, probably because they are incredibly old. The problem with the new dialogs being asynchronous is that for example the hotkeys, the server protocol and honestly any sort of async download that's still running in the background can all mess with the timer while the dialog is open. This could lead to all sorts of weird issues, like the timer being in a different state than what the dialog expects, the timer being reset twice and creating two dialogs that are open at the same time and possibly even memory corruption in the Rust code.
This commit ensures that the timer can not be interacted with while it is "locked for interaction". In fact we already had such a notion where when you navigate to the …

Clean up some async race conditions & CSS fixes

---

src/index.tsx
src/indexDelayed.ts

We introduce a new `indexDelayed.ts` file that bundles all the imports that are used in the `index.ts` file. They are not imported directly there, because we want to keep the size of the `index.html` as small as possible, so it can focus on requesting the WASM file as soon as possible. This should result in the `indexDelayed.ts` bundle containing basically all the JS. This JS bundle and the WASM file should then be requested in parallel. While it would be possible to request these all individually over in the `index.ts`, browsers don't actually like doing too many requests in parallel and it turns out that big JavaScript files actually compress better than having many small ones. The WASM file also is pretty big, so ideally we are not bottlenecked by the large JS file. If necessary, we …

Request only a single JS bundle from `index.ts`

---

src-tauri/src/main.rs
src/storage/index.tsx
src/ui/LiveSplit.tsx
src/ui/MainSettings.tsx

This adds support for the `Always On Top` setting in the Tauri version of LiveSplit One. This setting allows you to keep the LiveSplit One window on top of all other windows.

Add `Always On Top` setting for Tauri

---

src-tauri/Cargo.toml
src-tauri/tauri.conf.json

WebAssembly needs a specific mime type to be allowed to be loaded. Tauri by default apparently can't send headers on Linux, unless you activate a specific feature, so the WebAssembly failed to load. Additionally, without the dialog feature, it also wasn't able to show the error message.

Fix Desktop Build on Linux

---

buildCore.js
test/rendering-test.js
wasm32-multivalue.json

With LLVM 19 they explicitly require using the `experimental-mv` ABI in addition to the `multivalue` LLVM feature (the latter is enabled by default now). Enabling the ABI is non-trivial and requires a full on custom Rust target. This adds `wasm32-multivalue.json` which is identical to `wasm32-unknown-unknown` except it sets the `experimental-mv` ABI. The target JSON format is very experimental by itself, so we may need to keep this up to date from time to time.

Enable Multivalue again

---

src/storage/index.tsx
src/ui/LSOCommandSink.ts
src/ui/MainSettings.tsx
src/ui/TimerView.tsx

This allows the user to choose between specifying segment times and split times when using the manual game timer.
Changelog: When using the **Manual Game Time Input**, you can now choose between specifying **Segment Times** and **Split Times**.

Add Setting for Manual Game Time Input Mode

---

src/ui/LSOCommandSink.ts
src/ui/LayoutEditor.tsx
src/ui/LiveSplit.tsx
src/ui/MainSettings.tsx
src/ui/RunEditor.tsx
src/ui/Settings.tsx

Instead of manually specifying the variables via text boxes, you can now choose them from dropdowns. This makes it easier to select the variables you want to use for the layout.
Changelog: You can now choose variables to display on the layout from dropdowns instead of manually specifying them via text boxes. Additionally, the layout editor now presents the custom variables as their own components to add to the layout. These are just preconfigured text components, but this makes it easier to add them to the layout.

Choose Variables from Dropdowns

---

buildCore.js
src-tauri/Cargo.lock
src/index.tsx

This allows us to skip letting `webpack` parse the wasm files, which means we are not blocked by its limitations anymore. This allows us to finally start using reference types.

Switch to the `web` Target of `wasm-bindgen`

---

buildCore.js
wasm32-multivalue.json

Apparently it's currently broken again in the recent Rust nightlies, so we have to disable it.

Disable Multivalue again

---

src/ui/ColorPicker.tsx

Apparently React behaves differently from Dioxus in that it doesn't allow changing inputs if they don't affect the value that they are bound to. So I spent some time on implementing some proper validation logic for the color inputs.

Allow Invalid Color Component Inputs

---

src/css/Table.scss

WebKit outside of Safari apparently ignores the background color of `<select>` elements. By using `appearance: none`, we can override the default style of the combo boxes and make them look consistent across all browsers.

Fix Style of Combo Boxes

---

src/css/variables.icss.scss
src/index.tsx
src/platform/Hotkeys.ts
src/type-definitions/assets.d.ts
src/type-definitions/images.d.ts
src/type-definitions/scss.d.ts
src/type-definitions/wasm.d.ts
src/ui/LiveSplit.tsx
src/ui/components/Layout.tsx
src/ui/views/LayoutEditor.tsx
src/ui/views/LayoutView.tsx
src/ui/views/MainSettings.tsx
src/ui/views/TimerView.tsx
src/util/AutoRefresh.tsx
tsconfig.json

This adds a new button to the sidebar that allows the user to pop out the entire layout into a separate child window. This makes it take up less of the screen and capture it more easily in OBS. I'm not sure if the button should be in the sidebar or not, but it's good enough for an initial implementation.
Changelog: You can now pop out the timer into a separate window.

Allow Popping Out the Timer Into a Separate Window

---

src/ui/LiveSplit.tsx

Chrome supports the [Document Picture-in-Picture API](https://developer.chrome.com/blog/the-future-of-picture-in-picture/), which allows us to create a popup window that is always on top, has a "return to tab" button, remembers its position and size, and has a more compact title bar. Considering not every browser supports this API, we automatically fall back to `window.open` if the API is not available.

Use Document Picture-in-Picture API if Available

---

src/platform/Hotkeys.ts
src/ui/LiveSplit.tsx
src/ui/views/SplitsSelection.tsx

The splits selection view did not correctly cause rerenders among other smaller bugs in there. I'm not sure how these bugs got introduced, as I barely made changes to the content of the functions, but these were completely different. Maybe this was Copilot's fault.
Additionally, when using Tauri, there was a bug where we had two hotkey implementations at the same time for the pop out windows. One was the global hotkey implementation and one was the local one we add to the pop out window. This caused the hotkey to be triggered twice.

Fix Bugs Introduced in Refactoring

---

src/ui/views/SplitsSelection.tsx

When the splits selection view is open, the sidebar and the view itself don't refresh properly anymore when in mobile mode. This is because the React compiler notices that with the way we wrote the code, these components have no reason to re-render. There is currently no proper `useMobile` hook. So while I implemented a quick workaround here, by forcing it to not memoize the individual props properly, we should refactor the sidebar code at some point to use a proper `useMobile` hook.

Fix Sidebar Not Refreshing in Splits Selection

---

src-tauri/Cargo.lock

When cleaning the sum of best, the message tries to be as helpful as possible by showing as much information about the problematic segments as possible. Part of that is information about the date of the attempt. However, as it turns out, the attempt may not actually exist. This shouldn't generally happen, but we can't trust the correctness of the splits files, so for whatever reason, the attempt may be missing. In that case, we simply skip that information.

Fix Panic When Cleaning Sum of Best
