LiveSplit/LiveSplitOne

src/ui/LiveSplit.tsx
Closes #11 
Closes #71 
Timer now resets before saving splits.
=> Match LiveSplit's saving behavior.

src/css/livesplit.css, src/layout/Title.tsx
=> Fix ellipses not appearing in Game/Category Name

src/css/livesplit.css, src/layout/Title.tsx
Correct Center text when Image is visible
Correct Single line vertical Alignment
Closes #80
=> Correct Title Component Layout

src/css/Splits.scss, src/layout/Split.tsx
=> Indent split names if at least one split has an icon

.babelrc, package-lock.json, package.json, webpack.config.js
=> Switch from babel-preset-env to @babel/preset-env

src/css/DragUpload.scss, src/ui/DragUpload.tsx, src/ui/LiveSplit.tsx, src/util/FileUtil.ts
A lot of code was borrowed from https://github.com/glacials/splits-io/blob/master/app/javascript/upload.js
Fix #97
=> Add ability to open splits via drag and drop

src/css/main.scss
Noticed a couple of minor tweaks could be made here.
=> Make minor fixes to the webkit scrollbars.

src/layout/Timer.tsx
=> Fix regression with timer shadows on background

src/ui/RunEditor.tsx
Changes to times are now submitted in `onBlur` instead of `onChange`.
Fix #8 
Fix #55
=> Fix live validation for segments in the Run Editor

package.json
The electron app wouldn't run for me without this change.
Is there a build step that I'm missing otherwise?
=> Update start:electron npm target

src/css/RunEditor.scss, src/layout/Text.tsx, src/ui/RunEditor.tsx, src/ui/Settings.tsx
This PR uses the changes in https://github.com/LiveSplit/livesplit-core/pull/201
For now, I added the ability to add a custom variable and modify a custom variable. The bindings don't currently have a way to remove a custom variable, so I guess that would have to be added first before I can add removal functionality. I'm also not sure exactly how we'll handle removal because the Settings component doesn't currently support anything like that.
We also want components to be able to display custom variables, but I guess that can come later as well.
=> Add support for custom variables

src/index.html, src/index.tsx
=> Load React asynchronously

src/css/ContextMenu.scss, src/css/DragUpload.scss, src/css/LiveSplit.scss, src/css/Markdown.scss, src/css/RunEditor.scss, src/css/SideBarContent.scss, src/css/Table.scss, src/css/Toggle.scss, src/css/main.scss, src/css/variables.scss, src/ui/RunEditor.tsx
=> Hide Run Editor tabs when they are not applicable

src/css/variables.scss
=> Change colors to have more contrast

.github/workflows/ci.yml, .github/workflows/tslint.json, package.json, src/api/EmoteList.ts, src/api/GameList.ts, src/api/SpeedrunCom.ts, src/layout/DetailedTimer.tsx, src/layout/KeyValueGeneric.tsx, src/layout/Split.tsx, src/layout/Splits.tsx, src/layout/Timer.tsx, src/layout/Title.tsx, src/ui/ColorPicker.tsx, src/ui/DragUpload.tsx, src/ui/Embed.tsx, src/ui/LiveSplit.tsx, src/ui/RunEditor.tsx, src/ui/Settings.tsx, src/ui/TextBox.tsx, src/util/FileUtil.ts, src/util/Markdown.tsx, tslint.json
We should rebase this branch onto master if it's outdated and get passing CI builds before merging. We should also rebase any open PRs onto master after this is merged and make sure that any linter errors are fixed.
=> Add tslint to CI

.github/workflows/ci.yml
=> Key the caches by the current two weeks

src/ui/LiveSplit.tsx, src/ui/SideBarContent.tsx
=> Add buttons to load the default splits and layout

package-lock.json, package.json, src/css/Layout.scss, src/css/LiveSplit.scss, src/css/SideBarContent.scss, src/layout/AutoRefreshLayout.tsx, src/layout/Component.tsx, src/layout/DetailedTimer.tsx, src/layout/DragAutoRefreshLayout.tsx, src/layout/Graph.tsx, src/layout/Layout.tsx, src/layout/Timer.tsx, src/ui/LayoutEditor.tsx, src/ui/LiveSplit.tsx, tslint.json
This resolves some of the issues in #46. There's no saving at the moment since this is LSO only and nothing is in livesplit-core.
=> Allow the layout to be resized horizontally

src/css/Splits.scss, src/layout/Split.tsx, src/layout/SplitLabels.tsx
=> Add an option to the Splits to show two rows

src/css/DetailedTimer.scss, src/css/KeyValue.scss, src/css/Splits.scss, src/css/Timer.scss, src/css/Title.scss, src/css/variables.scss, src/layout/Split.tsx, src/layout/Title.tsx
The Title component is quite a bit different now, but its sizes should match the KeyValue component.
Fix #246, fix #247, fix #248
=> Fix styling in Splits and Title

src/css/LiveSplit.scss, src/css/browser_source.scss, src/css/main.scss, src/css/mobile.scss, src/css/variables.scss, src/layout/AutoRefreshLayout.tsx, src/layout/Layout.tsx, src/ui/LiveSplit.tsx
=> Adjust styling for mobile and OBS browser source

src/css/mobile.scss
=> Fix drop region positioning on mobile

src/css/DetailedTimer.scss, src/css/KeyValue.scss, src/css/Layout.scss, src/css/Separator.scss, src/css/Splits.scss, src/css/Timer.scss, src/css/Title.scss, src/css/variables.scss, src/layout/DetailedTimer.tsx, src/layout/Timer.tsx, src/type-definitions/scss.d.ts
=> Change styling to mostly match the native renderer

src/css/Table.scss, src/css/Time.scss, src/css/main.scss, test/rendering-test.js
=> Remove the Roboto font

src/css/font-awesome.css, src/css/main.scss, src/index.html, src/ui/LayoutEditor.tsx, src/ui/LiveSplit.tsx, src/ui/SideBarContent.tsx
=> Fix issues with the Chrome Dev Tools Audit

src/css/Title.scss, test/rendering-test.js
=> Fix size of game icon to match the two row split icon size

src/css/ContextMenu.scss, src/css/DragUpload.scss, src/css/HotkeyButton.scss, src/css/LayoutEditor.scss, src/css/LiveSplit.scss, src/css/RunEditor.scss, src/css/SettingsEditor.scss, src/css/SideBarContent.scss, src/css/Table.scss, src/css/main.scss, src/css/mobile.scss, src/css/variables.scss, src/ui/LayoutEditor.tsx, src/ui/LiveSplit.tsx, src/ui/RunEditor.tsx, src/ui/Settings.tsx
Probably the coolest part of these changes is this mixin for mobile logic:
```
@mixin mobile {
.is-mobile & {
@content;
}
}
```
This allows us to implement mobile logic throughout the SCSS rather than restricting it to a separate file. This makes conditional mobile logic super easy and clean compared to what it would be otherwise.
Fix #38
=> Improve UI consistency and mobile layout

src/css/Markdown.scss
=> Fix header line height in markdown

package-lock.json, package.json, src/index.tsx, src/storage/index.tsx, src/ui/LiveSplit.tsx, src/ui/RunEditor.tsx, src/util/FileUtil.ts, src/util/SplitsIO.ts
Fix #256
I'm opening this as a draft PR because I'm not sure how to approach storing the data as raw bytes or implementing compression for the splits files.
=> Switch to IndexedDB

src/ui/LiveSplit.tsx, src/ui/RunEditor.tsx, src/ui/SideBarContent.tsx
[Splits.io brand guidelines](https://splits.io/brand)
=> Change splits/io to Splits.io

.github/workflows/ci.yml
=> Use actions-rs/install for wasm-gc and wasm-bindgen-cli

src/ui/LiveSplit.tsx
=> Fix resizing logic when switching between mobile and desktop

src/css/HotkeyButton.scss, src/ui/HotkeyButton.tsx, test/rendering-test.js
I verified that this works on Mac with Firefox.
Fix #160
=> Make hotkey buttons not rely on focus and blur anymore

package-lock.json, package.json, src/css/ColorPicker.scss, src/css/RunEditor.scss, src/css/Table.scss, src/css/ToggleCheckbox.scss, src/css/variables.scss, src/ui/ColorPicker.tsx, src/ui/HotkeyButton.tsx, src/ui/RunEditor.tsx, src/ui/Settings.tsx, src/ui/ToggleCheckbox.tsx
=> Replace checkboxes with toggles

src/ui/HotkeyButton.tsx
Instead of showing user unfriendly key codes, we want to show the actual characters that the keys resolve to based on the user's keyboard layout. This is a fairly experimental Web API, but it's the best we can do at the moment.
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardLayoutMap
=> Resolve Keys based on the Keyboard Layout

src/ui/HotkeyButton.tsx
=> Fix hotkey buttons keeping the listener even after a blur

.github/workflows/ci.yml, package-lock.json, src/ui/HotkeyButton.tsx
This adds support for hotkey modifiers, such as Ctrl, Alt, Shift and the Meta key. On top of that I ran `npm update` to truly update all the packages to their latest semver compatible versions, which `dependabot` doesn't seem to do for us. This also includes other updates in `livesplit-core` that were done since the last update, such as the precise formatting and parsing of the time stamps.
=> Implement Hotkey Modifiers

src/css/Markdown.scss, src/css/RunEditor.scss, src/ui/RunEditor.tsx, src/util/Markdown.tsx
This brings back the leaderboard flags. This time however not as emojis, but by simply using the flags from speedrun.com directly.
=> Bring back the leaderboard flags

src/api/SpeedrunCom.ts, src/css/Tooltip.scss, src/ui/RunEditor.tsx, src/ui/Settings.tsx, tsconfig.json
This adds tooltips to all settings. It's not optimal yet, because it doesn't support mobile yet, where you don't have a cursor that could hover the settings.
=> Add Tooltips

.github/workflows/ci.yml, webpack.config.js
This is necessary for the changelog generation to work correctly. Additionally this includes an improvement to sort the contributors alphabetically, if they have the same amount of contributions.
=> Clone the entire history in the CI workflow

.github/workflows/ci.yml
=> Fix `binaryen` usage in CI

README.md
The releases were added in #951
=> Add desktop build to README

.github/workflows/ci.yml, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/capabilities/migrated.json, src-tauri/src/main.rs, src-tauri/tauri.conf.json, src/platform/CORS.ts, src/platform/Hotkeys.ts, src/type-definitions/tauri.d.ts, src/ui/LiveSplit.tsx
This should hopefully resolve some of the issues.
=> Update to Tauri 2

src-tauri/Cargo.lock
This adds the ability to specify an optional text shadow in the general layout settings.
Changelog: Text shadows are now supported and enabled by default. You can customize the color or disable text shadows entirely in the layout settings.
=> Add Support for Text Shadows
